### PR TITLE
feat: expose more functions to adlib-actions

### PR DESCRIPTION
**Pull request by Julusian**
This needs some thought as to what properties it should be possible to change, and some general tidying.

The aim is to let adlib-actions change the transition on the next part.

cc @thomasslee97

### CODE REVIEW

**Comment by thomasslee97** [comment]
I'd suggest allowing `autoNext`, `autoNextOverlap` and `disableOutTransition` to be modified for transitions that play over the whole part (TV 2 use case)

**Comment by Julusian** [comment]
ok. I am wondering if I was being too strict with it yesterday. Perhaps we should let the actions change anything, except for invalid, invalidReason, floated, gap and externalId.

But should we allow the same level of control over the current and next part? It will be easy to cause some glitches in playback/odd behaviour, but so could changing or removing a piece that is currently on air. As long as it can only cause playout glitches, and not get sofie confused then from the point of view of sofie core, do we care?

**Comment by thomasslee97** [comment]
Hmm, I guess there is a level of "blueprints must be sensible" here, after all you can completely wipe the timeline in onTimelineGenerate.

Modifying MetaData on the current part seems safe, I could also see the case for setting a duration + autonext if you want to transition out of the current part as long as that's safe for Sofie to do. Certainly I don't think you should be able to set invalid / gap / floated on the current part. Again, I _could_ see the use for setting the next part as invalid but I don't have a need for it at the moment.

**Comment by Julusian** [comment]
> Hmm, I guess there is a level of "blueprints must be sensible" here, after all you can completely wipe the timeline in onTimelineGenerate.

Yeah. There are ways to do worse things, so maybe we shouldnt worry as long as we block changes some known bad changes.
When I continue playing with this, I shall change it to almost every property there then

> Again, I could see the use for setting the next part as invalid but I don't have a need for it at the moment.

Setting those would just break things though. As once the instance is invalid we would need to update the next. This will look through the parts (not instances) and most likely choose the same one again as the part is not invalid. Plus if you were able to set a part to invalid, there wouldnt be a way to un-invalid it, as the actions only let you work on the current and nexted parts

**Comment by thomasslee97** [comment]
Ah! Good point

**Pull request merged**
