### PR TITLE
chore: clean up un-used properties

### PR DESCRIPTION
**Pull request by jesperstarkar**
Removes un-used properties in source layers. The motivation to do so is to be able to clean up the UI, avoid confusion, write less code, have more readable code and better maintainability.

### CODE REVIEW

**Comment by Julusian** [comment]
Is there a matching PR/branch for core?

**Comment by jesperstarkar** [comment]
No, it was suggested to not do anything more, to honour the current workflow aka leave it.

**Comment by jesperstarkar** [comment]
That said, I did so locally, and it felt small and safe.

**Comment by jstarpl** [comment]
Yeah, I would say that if we are removing it from the blueprints-integration, it would make sense to remove it from the UI in core as well.

**Comment by Julusian** [comment]
Yeah, as these are unused properties it should be a very quick deletion of a few erroring lines in core. So I am happy to merge and just do it once r15 has been fully merged and done.

**Comment by Julusian** [comment]
This has been manually merged

**Pull request closed without merging**
